### ISSUE TITLE
ble: make API non blocking

### ISSUE THREAD

**Issue by tralamazza** [tralamazza/micropython#65] opened 2017-06-03 20:58 UTC
no busy ➿

**Comment by glennrub** [comment] 2018-07-19 18:37
In order to clean up a bit i'm closing this issue in this repo as the continuation of the nrf-port development should happen in mainline micropython repository after the merge. If the issue is still applicable it could be raised towards mainline repo.

**Closed as completed by glennrub** 2018-07-19 18:37 UTC
