### ISSUE TITLE
DFU/bootloader support

### ISSUE THREAD

**Issue by aykevl** [tralamazza/micropython#146] opened 2018-01-07 23:52 UTC
I have written a DFU (device firmware updater) that's written in the 4kB MBR of the SoftDevice. At the moment it is just over 1kB in size, so some extra features could be added (e.g. update on button press at reset, update over serial, more safety, etc.).
A Python script to send a hex file over BLE can be found here: https://github.com/aykevl/pynus/blob/master/dfu.py

This is the branch implementing DFU: https://github.com/tralamazza/micropython/compare/master...aykevl:nrf-dfu-mbr-wip

There are a few things left to do, but I'm putting it here because these are only relatively small changes and some feedback would be welcome.

TODO: 

- [x] test mbr/bootloader mode on nRF51 (should work, but as there were a lot of changes it should be tested again)
- [x] test bootloader mode on nRF52 (find UICR.BOOTLOADERADDR address)
- [ ] support bootloaderaddr in mergehex.py
- [x] fix bootloaderaddr in 'info' characteristic
- [x] optionally load parameters (application start address etc.) from the info struct in the SoftDevice instead of hardcoding it - this makes it possible to update the SoftDevice (including resizing it!) without updating the DFU.
- [x] Python 2 support in mergehex.py
- [x] fix "buffer too small" errors (see https://github.com/tralamazza/micropython/pull/147)

**Comment by glennrub** [comment] 2018-07-19 18:34
In order to clean up a bit i'm closing this issue in this repo as the continuation of the nrf-port development should happen in mainline micropython repository after the merge. If the issue is still applicable it could be raised towards mainline repo.

**Closed as completed by glennrub** 2018-07-19 18:34 UTC
